export const FETCH_LIST_POST ='FETCH_LIST_POST';
export const FETCH_LIST_POST_SUCCESS ='FETCH_LIST_POST_SUCCESS';
export const FETCH_LIST_POST_FAILED ='FETCH_LIST_POST_FAILED';


export const FETCH_LIST_CATEGORY ='FETCH_LIST_CATEGORY';
export const FETCH_LIST_CATEGORY_SUCCESS ='FETCH_LIST_CATEGORY_SUCCESS';
export const FETCH_LIST_CATEGORY_FAILED ='FETCH_LIST_CATEGORY_FAILED';


export const LOGIN ='LOGIN';
export const LOGIN_SUCCESS ='LOGIN_SUCCESS';
export const LOGIN_FAILED ='LOGIN_FAILED';


export const USER_INIT ='USER_INIT';
export const USER_INIT_SUCCESS ='USER_INIT_SUCCESS';
export const USER_INIT_FAILED ='USER_INIT_FAILED';


export const UPDATE_PROFILE ='UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS ='UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED ='UPDATE_PROFILE_FAILED';