export const FETCH_LIST_POST ='FETCH_LIST_POST';
export const FETCH_LIST_POST_SUCCESS ='FETCH_LIST_POST_SUCCESS';
export const FETCH_LIST_POST_FAILED ='FETCH_LIST_POST_FAILED';


export const FETCH_LIST_CATEGORY ='FETCH_LIST_CATEGORY';
export const FETCH_LIST_CATEGORY_SUCCESS ='FETCH_LIST_CATEGORY_SUCCESS';
export const FETCH_LIST_CATEGORY_FAILED ='FETCH_LIST_CATEGORY_FAILED';