export const FETCH_LIST_POST ='FETCH_LIST_POST';
export const FETCH_LIST_POST_SUCCESS ='FETCH_LIST_POST_SUCCESS';
export const FETCH_LIST_POST_FAILED ='FETCH_LIST_POST_FAILED';


export const FETCH_LIST_CATEGORY ='FETCH_LIST_CATEGORY';
export const FETCH_LIST_CATEGORY_SUCCESS ='FETCH_LIST_CATEGORY_SUCCESS';
export const FETCH_LIST_CATEGORY_FAILED ='FETCH_LIST_CATEGORY_FAILED';


export const LOGIN ='LOGIN';
export const LOGIN_SUCCESS ='LOGIN_SUCCESS';
export const LOGIN_FAILED ='LOGIN_FAILED';


export const USER_INIT ='USER_INIT';
export const USER_INIT_SUCCESS ='USER_INIT_SUCCESS';
export const USER_INIT_FAILED ='USER_INIT_FAILED';


export const UPDATE_PROFILE ='UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS ='UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED ='UPDATE_PROFILE_FAILED';


export const FETCH_LIST_POST_NEWEST ='FETCH_LIST_POST_NEWEST';
export const FETCH_LIST_POST_NEWEST_SUCCESS ='FETCH_LIST_POST_NEWEST_SUCCESS';
export const FETCH_LIST_POST_NEWEST_FAILED ='FETCH_LIST_POST_NEWEST_FAILED';

export const FETCH_LIST_POST_TRENDING ='FETCH_LIST_POST_TRENDING';
export const FETCH_LIST_POST_TRENDING_SUCCESS ='FETCH_LIST_POST_TRENDING_SUCCESS';
export const FETCH_LIST_POST_TRENDING_FAILED ='FETCH_LIST_POST_TRENDING_FAILED';

export const FETCH_LIST_POST_NEWEST_REMAINING ='FETCH_LIST_POST_NEWEST_REMAINING';
export const FETCH_LIST_POST_NEWEST_REMAINING_SUCCESS ='FETCH_LIST_POST_NEWEST_REMAINING_SUCCESS';
export const FETCH_LIST_POST_NEWEST_REMAINING_FAILED ='FETCH_LIST_POST_NEWEST_REMAINING_FAILED';


export const FETCH_POST_DETAILS ='FETCH_POST_DETAILS';
export const FETCH_POST_DETAILS_SUCCESS ='FETCH_POST_DETAILS_SUCCESS';
export const FETCH_POST_DETAILS_FAILED ='FETCH_POST_DETAILS_FAILED';

export const FETCH_LIST_TAG ='FETCH_LIST_TAG';
export const FETCH_LIST_TAG_SUCCESS ='FETCH_LIST_TAG_SUCCESS';
export const FETCH_LIST_TAG_FAILED ='FETCH_LIST_TAG_FAILED';


export const ADD_POST ='ADD_POST';
export const ADD_POST_SUCCESS ='ADD_POST_SUCCESS';
export const ADD_POST_FAILED ='ADD_POST_FAILED';